/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Ltn98bsO9qv
 */
import { CardContent, Card } from "@/components/ui/card"

export function FlightCard({ flightInfo:{flightNumber, company, departure, arrival, departs, arrives, duration, gate }}) {
  return (
    <Card className="w-full max-w-sm mx-auto">
      <CardContent className="p-6">
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-4">
            <img
              alt="Airline"
              className="rounded-lg"
              height="32"
              src="/CA-logo.png"
              style={{
                aspectRatio: "32/32",
                objectFit: "cover",
              }}
              width="32"
            />
            <div className="grid gap-1.5">
              <h3 className="text-sm font-bold leading-none">{company}</h3>
              <p className="text-xs leading-none text-gray-500">{flightNumber}</p>
            </div>
          </div>
        </div>
        <div className="border-t border-gray-200 my-6" />
        <div className="grid gap-1.5 text-sm">
          <div className="grid grid-cols-2 items-center gap-1.5">
            <p className="text-sm font-semibold">Departure</p>
            <p className="text-right">{departure}</p>
          </div>
          <div className="grid grid-cols-2 items-center gap-1.5">
            <p className="text-sm font-semibold">Arrival</p>
            <p className="text-right">{arrival}</p>
          </div>
          <div className="grid grid-cols-2 items-center gap-1.5">
            <p className="text-sm font-semibold">Departs</p>
            <p className="text-right">{departs}</p>
          </div>
          <div className="grid grid-cols-2 items-center gap-1.5">
            <p className="text-sm font-semibold">Arrives</p>
            <p className="text-right">{arrives}</p>
          </div>
          <div className="grid grid-cols-2 items-center gap-1.5">
            <p className="text-sm font-semibold">Duration</p>
            <p className="text-right">{duration}</p>
          </div>
          <div className="grid grid-cols-2 items-center gap-1.5">
            <p className="text-sm font-semibold">Gate</p>
            <p className="text-right">{gate}</p>
          </div>
        </div>
      </CardContent>
    </Card>
  )
}
