/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Y04CmKHPFAi
 */
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"

export function WeatherCard({ weatherInfo }) {
  return (
    <Card className="w-full max-w-sm">
      <CardHeader className="flex flex-col items-center space-y-1.5">
        <div className="flex items-center space-x-2">
          <div className="grid gap-0.5">
            <CardTitle>{weatherInfo.city}</CardTitle>
            <CardDescription>{weatherInfo.weather}</CardDescription>
          </div>
          <img
            alt="Weather icon"
            className="rounded-lg overflow-hidden ring-1 ring-gray-200 dark:ring-gray-800"
            height="64"
            src="/placeholder.svg"
            style={{
              aspectRatio: "64/64",
              objectFit: "cover",
            }}
            width="64"
          />
        </div>
        <div className="flex items-center space-x-2">
          <ThermometerIcon className="w-4 h-4" />
          <UmbrellaIcon className="w-4 h-4" />
          <WindIcon className="w-4 h-4" />
          <SunriseIcon className="w-4 h-4" />
          <SunsetIcon className="w-4 h-4" />
        </div>
      </CardHeader>
      <CardContent className="flex flex-col items-center space-y-1.5">
        <div className="grid gap-0.5">
          <p className="text-2xl font-semibold tracking-tighter">{weatherInfo.temperature}°</p>
          <p className="text-sm font-medium tracking-tight text-gray-500 dark:text-gray-400">体感温度 {weatherInfo.temperature}°</p>
        </div>
        <div className="grid gap-1.5 text-sm text-center">
          <li>0% Precipitation</li>
          <li>Humidity {weatherInfo.humidity}%</li>
          <li>Wind {weatherInfo.windpower} km/h</li>
          <li>Sunrise 06:33</li>
          <li>Sunset 19:52</li>
        </div>
      </CardContent>
    </Card>
  )
}


function ThermometerIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14 4v10.54a4 4 0 1 1-4 0V4a2 2 0 0 1 4 0Z" />
    </svg>
  )
}


function UmbrellaIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 12a10.06 10.06 1 0 0-20 0Z" />
      <path d="M12 12v8a2 2 0 0 0 4 0" />
      <path d="M12 2v1" />
    </svg>
  )
}


function WindIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17.7 7.7a2.5 2.5 0 1 1 1.8 4.3H2" />
      <path d="M9.6 4.6A2 2 0 1 1 11 8H2" />
      <path d="M12.6 19.4A2 2 0 1 0 14 16H2" />
    </svg>
  )
}


function SunriseIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 2v8" />
      <path d="m4.93 10.93 1.41 1.41" />
      <path d="M2 18h2" />
      <path d="M20 18h2" />
      <path d="m19.07 10.93-1.41 1.41" />
      <path d="M22 22H2" />
      <path d="m8 6 4-4 4 4" />
      <path d="M16 18a4 4 0 0 0-8 0" />
    </svg>
  )
}


function SunsetIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 10V2" />
      <path d="m4.93 10.93 1.41 1.41" />
      <path d="M2 18h2" />
      <path d="M20 18h2" />
      <path d="m19.07 10.93-1.41 1.41" />
      <path d="M22 22H2" />
      <path d="m16 6-4 4-4-4" />
      <path d="M16 18a4 4 0 0 0-8 0" />
    </svg>
  )
}
